◇ injected env (88) from .env // tip: ⌁ auth for agents [www.vestauth.com]
-- Backup of blockchain.valoores_customer_kyc before Phase 14 safe source_record_id patch
-- Generated at: 2026-07-03T10:03:52.459Z
 SELECT 'VALOORES'::text AS source_system,
    'CUSTOMER_KYC'::text AS source_entity,
    source_record_id,
    COALESCE(NULLIF(customer_id, ''::text), NULLIF(customer_def_id, ''::text), source_record_id) AS business_reference,
    'CUSTOMER_KYC'::text AS record_type,
    COALESCE(NULLIF(customer_status_code, ''::text), 'UNKNOWN'::text) AS record_status,
    COALESCE(NULLIF(kyc_update_date, ''::text), NULLIF(customer_update_date, ''::text), NULLIF(last_update_date, ''::text), NULLIF(kyc_creation_date, ''::text), NULLIF(customer_creation_date, ''::text), NULLIF(last_extraction_date, ''::text), now()::text) AS standardized_event_timestamp,
    'V1'::text AS proof_version,
    hash_input,
    source_module,
    customer_id,
    customer_def_id,
    object_id,
    object_pk_value,
    customer_status_code,
    customer_status_date,
    party_id,
    party_type_code,
    party_sub_type_code,
    customer_nature_code,
    is_valid_flag,
    is_displayed_flag,
    data_source_code,
    business_group_id,
    currency_id,
    language_id,
    society_id,
    customer_profile_fingerprint,
    kyc_object_fingerprint,
    customer_creation_date,
    customer_update_date,
    last_update_date,
    last_extraction_date,
    kyc_creation_date,
    kyc_update_date,
    hash_md5
   FROM blockchain.valoores_customer_kyc_legacy_20260703 legacy;;
