◇ injected env (88) from .env // tip: ⌘ multiple files { path: ['.env.local', '.env'] }
-- Backup of blockchain.valoores_customer_kyc before Phase 14 compatibility patch
-- Generated at: 2026-07-03T08:50:03.233Z
 WITH source_data AS (
         SELECT a.customer_id,
            b.customer_def_id,
            b.object_id,
            b.object_pk_value,
            b.object_content,
            a.status_code,
            a.status_bdate,
            a.customer_internal_code,
            a.party_id,
            a.party_type_code,
            a.party_sub_type,
            a.customer_nature,
            a.is_valid,
            a.is_customer_displayed,
            a.data_source,
            a.bsn_group_id,
            a.cur_id,
            a.lan_id,
            a.soc_id,
            a.creation_date AS customer_creation_date,
            a.update_date AS customer_update_date,
            a.last_update_date,
            a.last_extraction_date,
            b.creation_date AS kyc_creation_date,
            b.update_date AS kyc_update_date,
            a.customer_name,
            a.customer_sname,
            a.customer_previous_name,
            a.customer_embossing_name,
            a.customer_first_name,
            a.customer_last_name,
            a.customer_father_name,
            a.customer_mother_name,
            a.customer_maiden_name,
            a.mother_name,
            a.mother_maiden_name,
            a.person_dob,
            a.birth_cou_id,
            a.birth_place_id,
            a.birth_nationality_id,
            a.registration_no,
            a.registration_date,
            a.registration_cou_id,
            a.registration_place_id,
            a.customer_reference,
            a.tech_customer_name,
            a.tech_updated_customer_name,
            a.tech_customer_profile_id,
            a.tech_account_no,
            a.adr_desc
           FROM ref_customer a
             JOIN cfg_customer_def b ON b.customer_id = a.customer_id
        ), normalized AS (
         SELECT 'CUSTOMER_KYC'::text AS source_module,
            concat(COALESCE(source_data.customer_id::text, 'NA'::text), ':', COALESCE(source_data.customer_def_id::text, 'NA'::text)) AS source_record_id,
            COALESCE(source_data.customer_id::text, 'NA'::text) AS customer_id,
            COALESCE(source_data.customer_def_id::text, 'NA'::text) AS customer_def_id,
            COALESCE(source_data.object_id::text, 'NA'::text) AS object_id,
            COALESCE(source_data.object_pk_value::text, 'NA'::text) AS object_pk_value,
            COALESCE(source_data.status_code::text, 'NA'::text) AS customer_status_code,
            COALESCE(to_char(source_data.status_bdate::timestamp with time zone, 'YYYY-MM-DD'::text), ''::text) AS customer_status_date,
            COALESCE(source_data.party_id::text, 'NA'::text) AS party_id,
            COALESCE(source_data.party_type_code::text, 'NA'::text) AS party_type_code,
            COALESCE(source_data.party_sub_type::text, 'NA'::text) AS party_sub_type_code,
            COALESCE(source_data.customer_nature::text, 'NA'::text) AS customer_nature_code,
            COALESCE(lower(btrim(source_data.is_valid::text)), ''::text) AS is_valid_flag,
            COALESCE(lower(btrim(source_data.is_customer_displayed::text)), ''::text) AS is_displayed_flag,
            COALESCE(source_data.data_source::text, 'NA'::text) AS data_source_code,
            COALESCE(source_data.bsn_group_id::text, 'NA'::text) AS business_group_id,
            COALESCE(source_data.cur_id::text, 'NA'::text) AS currency_id,
            COALESCE(source_data.lan_id::text, 'NA'::text) AS language_id,
            COALESCE(source_data.soc_id::text, 'NA'::text) AS society_id,
            md5(concat_ws('|'::text, COALESCE(lower(btrim(regexp_replace(source_data.customer_internal_code::text, '\s+'::text, ' '::text, 'g'::text))), ''::text), COALESCE(lower(btrim(regexp_replace(source_data.customer_name::text, '\s+'::text, ' '::text, 'g'::text))), ''::text), COALESCE(lower(btrim(regexp_replace(source_data.customer_sname::text, '\s+'::text, ' '::text, 'g'::text))), ''::text), COALESCE(lower(btrim(regexp_replace(source_data.customer_previous_name::text, '\s+'::text, ' '::text, 'g'::text))), ''::text), COALESCE(lower(btrim(regexp_replace(source_data.customer_embossing_name::text, '\s+'::text, ' '::text, 'g'::text))), ''::text), COALESCE(lower(btrim(regexp_replace(source_data.customer_first_name::text, '\s+'::text, ' '::text, 'g'::text))), ''::text), COALESCE(lower(btrim(regexp_replace(source_data.customer_last_name::text, '\s+'::text, ' '::text, 'g'::text))), ''::text), COALESCE(lower(btrim(regexp_replace(source_data.customer_father_name::text, '\s+'::text, ' '::text, 'g'::text))), ''::text), COALESCE(lower(btrim(regexp_replace(source_data.customer_mother_name::text, '\s+'::text, ' '::text, 'g'::text))), ''::text), COALESCE(lower(btrim(regexp_replace(source_data.customer_maiden_name::text, '\s+'::text, ' '::text, 'g'::text))), ''::text), COALESCE(lower(btrim(regexp_replace(source_data.mother_name::text, '\s+'::text, ' '::text, 'g'::text))), ''::text), COALESCE(lower(btrim(regexp_replace(source_data.mother_maiden_name::text, '\s+'::text, ' '::text, 'g'::text))), ''::text), COALESCE(to_char(source_data.person_dob::timestamp with time zone, 'YYYY-MM-DD'::text), ''::text), COALESCE(source_data.birth_cou_id::text, ''::text), COALESCE(source_data.birth_place_id::text, ''::text), COALESCE(source_data.birth_nationality_id::text, ''::text), COALESCE(lower(btrim(regexp_replace(source_data.registration_no::text, '\s+'::text, ' '::text, 'g'::text))), ''::text), COALESCE(to_char(source_data.registration_date::timestamp with time zone, 'YYYY-MM-DD'::text), ''::text), COALESCE(source_data.registration_cou_id::text, ''::text), COALESCE(source_data.registration_place_id::text, ''::text), COALESCE(lower(btrim(regexp_replace(source_data.customer_reference::text, '\s+'::text, ' '::text, 'g'::text))), ''::text), COALESCE(lower(btrim(regexp_replace(source_data.tech_customer_name::text, '\s+'::text, ' '::text, 'g'::text))), ''::text), COALESCE(lower(btrim(regexp_replace(source_data.tech_updated_customer_name::text, '\s+'::text, ' '::text, 'g'::text))), ''::text), COALESCE(lower(btrim(regexp_replace(source_data.tech_customer_profile_id::text, '\s+'::text, ' '::text, 'g'::text))), ''::text), COALESCE(lower(btrim(regexp_replace(source_data.tech_account_no::text, '\s+'::text, ' '::text, 'g'::text))), ''::text), COALESCE(lower(btrim(regexp_replace(source_data.adr_desc::text, '\s+'::text, ' '::text, 'g'::text))), ''::text))) AS customer_profile_fingerprint,
            md5(COALESCE(source_data.object_content::text, ''::text)) AS kyc_object_fingerprint,
            COALESCE(to_char(source_data.customer_creation_date::timestamp with time zone, 'YYYY-MM-DD'::text), ''::text) AS customer_creation_date,
            COALESCE(to_char(source_data.customer_update_date::timestamp with time zone, 'YYYY-MM-DD'::text), ''::text) AS customer_update_date,
            COALESCE(to_char(source_data.last_update_date::timestamp with time zone, 'YYYY-MM-DD'::text), ''::text) AS last_update_date,
            COALESCE(to_char(source_data.last_extraction_date::timestamp with time zone, 'YYYY-MM-DD'::text), ''::text) AS last_extraction_date,
            COALESCE(to_char(source_data.kyc_creation_date::timestamp with time zone, 'YYYY-MM-DD'::text), ''::text) AS kyc_creation_date,
            COALESCE(to_char(source_data.kyc_update_date::timestamp with time zone, 'YYYY-MM-DD'::text), ''::text) AS kyc_update_date
           FROM source_data
        ), hash_ready AS (
         SELECT normalized.source_module,
            normalized.source_record_id,
            normalized.customer_id,
            normalized.customer_def_id,
            normalized.object_id,
            normalized.object_pk_value,
            normalized.customer_status_code,
            normalized.customer_status_date,
            normalized.party_id,
            normalized.party_type_code,
            normalized.party_sub_type_code,
            normalized.customer_nature_code,
            normalized.is_valid_flag,
            normalized.is_displayed_flag,
            normalized.data_source_code,
            normalized.business_group_id,
            normalized.currency_id,
            normalized.language_id,
            normalized.society_id,
            normalized.customer_profile_fingerprint,
            normalized.kyc_object_fingerprint,
            normalized.customer_creation_date,
            normalized.customer_update_date,
            normalized.last_update_date,
            normalized.last_extraction_date,
            normalized.kyc_creation_date,
            normalized.kyc_update_date,
            concat_ws('|'::text, normalized.source_module, normalized.source_record_id, normalized.customer_id, normalized.customer_def_id, normalized.object_id, normalized.object_pk_value, normalized.customer_status_code, normalized.customer_status_date, normalized.party_id, normalized.party_type_code, normalized.party_sub_type_code, normalized.customer_nature_code, normalized.is_valid_flag, normalized.is_displayed_flag, normalized.data_source_code, normalized.business_group_id, normalized.currency_id, normalized.language_id, normalized.society_id, normalized.customer_profile_fingerprint, normalized.kyc_object_fingerprint, normalized.customer_creation_date, normalized.customer_update_date, normalized.last_update_date, normalized.last_extraction_date, normalized.kyc_creation_date, normalized.kyc_update_date) AS hash_input
           FROM normalized
        )
 SELECT source_module,
    source_record_id,
    customer_id,
    customer_def_id,
    object_id,
    object_pk_value,
    customer_status_code,
    customer_status_date,
    party_id,
    party_type_code,
    party_sub_type_code,
    customer_nature_code,
    is_valid_flag,
    is_displayed_flag,
    data_source_code,
    business_group_id,
    currency_id,
    language_id,
    society_id,
    customer_profile_fingerprint,
    kyc_object_fingerprint,
    customer_creation_date,
    customer_update_date,
    last_update_date,
    last_extraction_date,
    kyc_creation_date,
    kyc_update_date,
    hash_input,
    md5(hash_input) AS hash_md5
   FROM hash_ready;;
