'use strict';

const { Contract } = require('fabric-contract-api');
const crypto = require('crypto');

/**
 * Blockchain Integration Project
 * Hyperledger Fabric JavaScript Chaincode
 *
 * Main Features:
 * - Create Wallet
 * - Login Wallet
 * - Transfer Between Wallets
 * - Transfer Wallet To Organization
 * - Get Wallet Balance
 * - Get Transaction History
 *
 * Important Notes:
 * - Passwords must NOT be stored in plain text.
 * - The API layer should hash the password before sending it to chaincode.
 * - Chaincode verifies the passwordHash only.
 * - JWT/session tokens should be generated by the API layer, not by chaincode.
 */
class KycWalletContract extends Contract {

    constructor() {
        super('KycWalletContract');
    }

    /**
     * Initializes the ledger.
     * This method can be called once after deployment if needed.
     */
    async InitLedger(ctx) {
        console.info('============= InitLedger Started =============');

        const metadata = {
            docType: 'CHAINCODE_METADATA',
            project: 'Blockchain Integration Project',
            chaincodeName: 'kyc-wallet-chaincode-js',
            version: '1.0.0',
            initializedAt: this._getTxTimestamp(ctx),
            initializedByTxId: ctx.stub.getTxID()
        };

        await ctx.stub.putState('CHAINCODE_METADATA', Buffer.from(JSON.stringify(metadata)));

        console.info('============= InitLedger Completed =============');

        return this._successResponse('Ledger initialized successfully', metadata);
    }

    /**
     * CreateWallet
     *
     * Purpose:
     * Creates a blockchain wallet for a verified customer.
     *
     * Input:
     * - customerId
     * - organizationId
     * - fullName
     * - nationalIdHash
     * - mobileHash
     * - emailHash
     * - passwordHash
     * - initialBalance
     *
     * Important:
     * Sensitive fields should be hashed before reaching chaincode.
     */
    async CreateWallet(
        ctx,
        customerId,
        organizationId,
        fullName,
        nationalIdHash,
        mobileHash,
        emailHash,
        passwordHash,
        initialBalance
    ) {
        this._required(customerId, 'customerId');
        this._required(organizationId, 'organizationId');
        this._required(fullName, 'fullName');
        this._required(passwordHash, 'passwordHash');

        const parsedInitialBalance = this._parseAmount(initialBalance, 'initialBalance');

        if (parsedInitialBalance < 0) {
            throw new Error('Initial balance cannot be negative');
        }

        const existingWalletByCustomer = await this._getWalletByCustomerId(ctx, customerId);

        if (existingWalletByCustomer) {
            throw new Error(`Wallet already exists for customerId: ${customerId}`);
        }

        const txId = ctx.stub.getTxID();
        const createdAt = this._getTxTimestamp(ctx);

        const walletAddress = this._generateWalletAddress(customerId, organizationId, txId);

        const walletKey = this._walletKey(walletAddress);

        const wallet = {
            docType: 'WALLET',
            walletAddress: walletAddress,
            customerId: customerId,
            organizationId: organizationId,
            fullName: fullName,

            /**
             * These values should be hashed by the API layer.
             * Do not store raw national ID, phone, or email on-chain.
             */
            nationalIdHash: nationalIdHash || null,
            mobileHash: mobileHash || null,
            emailHash: emailHash || null,

            /**
             * Store only hash, never plain password.
             */
            passwordHash: passwordHash,

            balance: parsedInitialBalance,
            currency: 'TOKEN',

            status: 'ACTIVE',
            createdAt: createdAt,
            updatedAt: createdAt,
            createdTxId: txId,
            updatedTxId: txId
        };

        await ctx.stub.putState(walletKey, Buffer.from(JSON.stringify(wallet)));

        const transaction = {
            docType: 'TRANSACTION',
            transactionId: txId,
            transactionType: 'WALLET_CREATED',
            fromWallet: null,
            toWallet: walletAddress,
            organizationId: organizationId,
            amount: parsedInitialBalance,
            currency: 'TOKEN',
            status: 'SUCCESS',
            riskLevel: 'LOW',
            description: 'Wallet created',
            createdAt: createdAt,
            createdTxId: txId
        };

        await ctx.stub.putState(this._transactionKey(txId), Buffer.from(JSON.stringify(transaction)));

        const safeWallet = this._removeSensitiveWalletFields(wallet);

        return this._successResponse('Wallet created successfully', {
            wallet: safeWallet,
            transaction: transaction
        });
    }

    /**
     * LoginWallet
     *
     * Purpose:
     * Verifies wallet login credentials.
     *
     * Input:
     * - walletAddress
     * - passwordHash
     *
     * Important:
     * This method does NOT create JWT tokens.
     * JWT/session token must be created by Blockchain API / Spring Boot layer.
     */
    async LoginWallet(ctx, walletAddress, passwordHash) {
        this._required(walletAddress, 'walletAddress');
        this._required(passwordHash, 'passwordHash');

        const wallet = await this._getWalletByAddress(ctx, walletAddress);

        if (!wallet) {
            throw new Error(`Wallet not found: ${walletAddress}`);
        }

        if (wallet.status !== 'ACTIVE') {
            throw new Error(`Wallet is not active. Current status: ${wallet.status}`);
        }

        if (wallet.passwordHash !== passwordHash) {
            throw new Error('Invalid wallet credentials');
        }

        const loginAudit = {
            docType: 'AUTH_AUDIT',
            authId: ctx.stub.getTxID(),
            walletAddress: walletAddress,
            customerId: wallet.customerId,
            organizationId: wallet.organizationId,
            loginStatus: 'SUCCESS',
            createdAt: this._getTxTimestamp(ctx),
            createdTxId: ctx.stub.getTxID()
        };

        await ctx.stub.putState(this._authAuditKey(loginAudit.authId), Buffer.from(JSON.stringify(loginAudit)));

        const safeWallet = this._removeSensitiveWalletFields(wallet);

        return this._successResponse('Wallet login successful', {
            wallet: safeWallet,
            authAudit: loginAudit
        });
    }

    /**
     * TransferBetweenWallets
     *
     * Purpose:
     * Transfers balance from one wallet to another wallet.
     *
     * Input:
     * - fromWalletAddress
     * - toWalletAddress
     * - amount
     * - description
     */
    async TransferBetweenWallets(ctx, fromWalletAddress, toWalletAddress, amount, description) {
        this._required(fromWalletAddress, 'fromWalletAddress');
        this._required(toWalletAddress, 'toWalletAddress');

        if (fromWalletAddress === toWalletAddress) {
            throw new Error('Sender wallet and receiver wallet cannot be the same');
        }

        const parsedAmount = this._parseAmount(amount, 'amount');

        if (parsedAmount <= 0) {
            throw new Error('Transfer amount must be greater than zero');
        }

        const fromWallet = await this._getWalletByAddress(ctx, fromWalletAddress);
        const toWallet = await this._getWalletByAddress(ctx, toWalletAddress);

        if (!fromWallet) {
            throw new Error(`Sender wallet not found: ${fromWalletAddress}`);
        }

        if (!toWallet) {
            throw new Error(`Receiver wallet not found: ${toWalletAddress}`);
        }

        this._validateWalletActive(fromWallet, 'Sender wallet');
        this._validateWalletActive(toWallet, 'Receiver wallet');

        if (fromWallet.balance < parsedAmount) {
            throw new Error('Insufficient wallet balance');
        }

        const txId = ctx.stub.getTxID();
        const createdAt = this._getTxTimestamp(ctx);

        fromWallet.balance = this._roundAmount(fromWallet.balance - parsedAmount);
        toWallet.balance = this._roundAmount(toWallet.balance + parsedAmount);

        fromWallet.updatedAt = createdAt;
        fromWallet.updatedTxId = txId;

        toWallet.updatedAt = createdAt;
        toWallet.updatedTxId = txId;

        const transaction = {
            docType: 'TRANSACTION',
            transactionId: txId,
            transactionType: 'WALLET_TO_WALLET',
            fromWallet: fromWalletAddress,
            toWallet: toWalletAddress,
            organizationId: null,
            amount: parsedAmount,
            currency: 'TOKEN',
            status: 'SUCCESS',
            riskLevel: this._calculateRiskLevel(parsedAmount),
            description: description || 'Wallet-to-wallet transfer',
            fromWalletBalanceAfter: fromWallet.balance,
            toWalletBalanceAfter: toWallet.balance,
            createdAt: createdAt,
            createdTxId: txId
        };

        await ctx.stub.putState(this._walletKey(fromWalletAddress), Buffer.from(JSON.stringify(fromWallet)));
        await ctx.stub.putState(this._walletKey(toWalletAddress), Buffer.from(JSON.stringify(toWallet)));
        await ctx.stub.putState(this._transactionKey(txId), Buffer.from(JSON.stringify(transaction)));

        return this._successResponse('Wallet-to-wallet transfer completed successfully', {
            transaction: transaction,
            fromWalletBalance: fromWallet.balance,
            toWalletBalance: toWallet.balance
        });
    }

    /**
     * TransferToOrganization
     *
     * Purpose:
     * Transfers amount from customer wallet to an organization.
     *
     * Input:
     * - fromWalletAddress
     * - organizationId
     * - amount
     * - description
     */
    async TransferToOrganization(ctx, fromWalletAddress, organizationId, amount, description) {
        this._required(fromWalletAddress, 'fromWalletAddress');
        this._required(organizationId, 'organizationId');

        const parsedAmount = this._parseAmount(amount, 'amount');

        if (parsedAmount <= 0) {
            throw new Error('Transfer amount must be greater than zero');
        }

        const fromWallet = await this._getWalletByAddress(ctx, fromWalletAddress);

        if (!fromWallet) {
            throw new Error(`Wallet not found: ${fromWalletAddress}`);
        }

        this._validateWalletActive(fromWallet, 'Wallet');

        if (fromWallet.balance < parsedAmount) {
            throw new Error('Insufficient wallet balance');
        }

        const txId = ctx.stub.getTxID();
        const createdAt = this._getTxTimestamp(ctx);

        fromWallet.balance = this._roundAmount(fromWallet.balance - parsedAmount);
        fromWallet.updatedAt = createdAt;
        fromWallet.updatedTxId = txId;

        const organizationLedgerKey = this._organizationBalanceKey(organizationId);
        const organizationBalanceBytes = await ctx.stub.getState(organizationLedgerKey);

        let organizationBalance;

        if (!organizationBalanceBytes || organizationBalanceBytes.length === 0) {
            organizationBalance = {
                docType: 'ORGANIZATION_BALANCE',
                organizationId: organizationId,
                balance: 0,
                currency: 'TOKEN',
                createdAt: createdAt,
                updatedAt: createdAt,
                createdTxId: txId,
                updatedTxId: txId
            };
        } else {
            organizationBalance = JSON.parse(organizationBalanceBytes.toString());
        }

        organizationBalance.balance = this._roundAmount(organizationBalance.balance + parsedAmount);
        organizationBalance.updatedAt = createdAt;
        organizationBalance.updatedTxId = txId;

        const transaction = {
            docType: 'TRANSACTION',
            transactionId: txId,
            transactionType: 'WALLET_TO_ORGANIZATION',
            fromWallet: fromWalletAddress,
            toWallet: null,
            organizationId: organizationId,
            amount: parsedAmount,
            currency: 'TOKEN',
            status: 'SUCCESS',
            riskLevel: this._calculateRiskLevel(parsedAmount),
            description: description || 'Wallet-to-organization transfer',
            fromWalletBalanceAfter: fromWallet.balance,
            organizationBalanceAfter: organizationBalance.balance,
            createdAt: createdAt,
            createdTxId: txId
        };

        await ctx.stub.putState(this._walletKey(fromWalletAddress), Buffer.from(JSON.stringify(fromWallet)));
        await ctx.stub.putState(organizationLedgerKey, Buffer.from(JSON.stringify(organizationBalance)));
        await ctx.stub.putState(this._transactionKey(txId), Buffer.from(JSON.stringify(transaction)));

        return this._successResponse('Wallet-to-organization transfer completed successfully', {
            transaction: transaction,
            walletBalance: fromWallet.balance,
            organizationBalance: organizationBalance.balance
        });
    }

    /**
     * GetWalletBalance
     *
     * Purpose:
     * Returns wallet balance.
     *
     * Input:
     * - walletAddress
     */
    async GetWalletBalance(ctx, walletAddress) {
        this._required(walletAddress, 'walletAddress');

        const wallet = await this._getWalletByAddress(ctx, walletAddress);

        if (!wallet) {
            throw new Error(`Wallet not found: ${walletAddress}`);
        }

        return this._successResponse('Wallet balance retrieved successfully', {
            walletAddress: wallet.walletAddress,
            customerId: wallet.customerId,
            organizationId: wallet.organizationId,
            balance: wallet.balance,
            currency: wallet.currency,
            status: wallet.status,
            updatedAt: wallet.updatedAt
        });
    }

    /**
     * GetTransactionHistory
     *
     * Purpose:
     * Returns transaction history for a wallet address.
     *
     * Input:
     * - walletAddress
     *
     * Uses CouchDB rich query.
     */
    async GetTransactionHistory(ctx, walletAddress) {
        this._required(walletAddress, 'walletAddress');

        const wallet = await this._getWalletByAddress(ctx, walletAddress);

        if (!wallet) {
            throw new Error(`Wallet not found: ${walletAddress}`);
        }

        const query = {
            selector: {
                docType: 'TRANSACTION',
                $or: [
                    {
                        fromWallet: walletAddress
                    },
                    {
                        toWallet: walletAddress
                    }
                ]
            },
            sort: [
                {
                    createdAt: 'desc'
                }
            ]
        };

        const results = await this._queryLedger(ctx, query);

        return this._successResponse('Transaction history retrieved successfully', {
            walletAddress: walletAddress,
            totalTransactions: results.length,
            transactions: results
        });
    }

    /**
     * GetWalletByCustomerId
     *
     * Optional helper query for API usage.
     */
    async GetWalletByCustomerId(ctx, customerId) {
        this._required(customerId, 'customerId');

        const wallet = await this._getWalletByCustomerId(ctx, customerId);

        if (!wallet) {
            throw new Error(`Wallet not found for customerId: ${customerId}`);
        }

        return this._successResponse('Wallet retrieved successfully', {
            wallet: this._removeSensitiveWalletFields(wallet)
        });
    }

    /**
     * GetOrganizationBalance
     *
     * Optional helper query for organization balance.
     */
    async GetOrganizationBalance(ctx, organizationId) {
        this._required(organizationId, 'organizationId');

        const organizationBalanceBytes = await ctx.stub.getState(this._organizationBalanceKey(organizationId));

        if (!organizationBalanceBytes || organizationBalanceBytes.length === 0) {
            return this._successResponse('Organization balance retrieved successfully', {
                organizationId: organizationId,
                balance: 0,
                currency: 'TOKEN'
            });
        }

        const organizationBalance = JSON.parse(organizationBalanceBytes.toString());

        return this._successResponse('Organization balance retrieved successfully', organizationBalance);
    }

    /**
     * GetTransactionById
     *
     * Optional helper query for direct transaction lookup.
     */
    async GetTransactionById(ctx, transactionId) {
        this._required(transactionId, 'transactionId');

        const transactionBytes = await ctx.stub.getState(this._transactionKey(transactionId));

        if (!transactionBytes || transactionBytes.length === 0) {
            throw new Error(`Transaction not found: ${transactionId}`);
        }

        const transaction = JSON.parse(transactionBytes.toString());

        return this._successResponse('Transaction retrieved successfully', transaction);
    }

    /**
     * WalletExists
     *
     * Optional helper method.
     */
    async WalletExists(ctx, walletAddress) {
        this._required(walletAddress, 'walletAddress');

        const walletBytes = await ctx.stub.getState(this._walletKey(walletAddress));

        return walletBytes && walletBytes.length > 0;
    }

    // ============================================================
    // Internal Helper Methods
    // ============================================================

    _walletKey(walletAddress) {
        return `WALLET_${walletAddress}`;
    }

    _transactionKey(transactionId) {
        return `TRANSACTION_${transactionId}`;
    }

    _authAuditKey(authId) {
        return `AUTH_AUDIT_${authId}`;
    }

    _organizationBalanceKey(organizationId) {
        return `ORGANIZATION_BALANCE_${organizationId}`;
    }

    _required(value, fieldName) {
        if (value === undefined || value === null || String(value).trim() === '') {
            throw new Error(`${fieldName} is required`);
        }
    }

    _parseAmount(value, fieldName) {
        this._required(value, fieldName);

        const parsed = Number(value);

        if (Number.isNaN(parsed)) {
            throw new Error(`${fieldName} must be a valid number`);
        }

        return this._roundAmount(parsed);
    }

    _roundAmount(value) {
        return Math.round(Number(value) * 100) / 100;
    }

    _validateWalletActive(wallet, label) {
        if (!wallet) {
            throw new Error(`${label} does not exist`);
        }

        if (wallet.status !== 'ACTIVE') {
            throw new Error(`${label} is not active. Current status: ${wallet.status}`);
        }
    }

    _generateWalletAddress(customerId, organizationId, txId) {
        const rawValue = `${customerId}|${organizationId}|${txId}`;
        const hash = crypto.createHash('sha256').update(rawValue).digest('hex');

        return `WALLET_${hash.substring(0, 40).toUpperCase()}`;
    }

    _calculateRiskLevel(amount) {
        const numericAmount = Number(amount);

        if (numericAmount >= 100000) {
            return 'HIGH';
        }

        if (numericAmount >= 10000) {
            return 'MEDIUM';
        }

        return 'LOW';
    }

    _getTxTimestamp(ctx) {
        const timestamp = ctx.stub.getTxTimestamp();

        const milliseconds = timestamp.seconds.low * 1000 + Math.floor(timestamp.nanos / 1000000);

        return new Date(milliseconds).toISOString();
    }

    async _getWalletByAddress(ctx, walletAddress) {
        const walletBytes = await ctx.stub.getState(this._walletKey(walletAddress));

        if (!walletBytes || walletBytes.length === 0) {
            return null;
        }

        return JSON.parse(walletBytes.toString());
    }

    async _getWalletByCustomerId(ctx, customerId) {
        const query = {
            selector: {
                docType: 'WALLET',
                customerId: customerId
            },
            limit: 1
        };

        const results = await this._queryLedger(ctx, query);

        if (!results || results.length === 0) {
            return null;
        }

        return results[0];
    }

    async _queryLedger(ctx, query) {
        const iterator = await ctx.stub.getQueryResult(JSON.stringify(query));
        const results = [];

        while (true) {
            const result = await iterator.next();

            if (result.value && result.value.value.toString()) {
                const record = JSON.parse(result.value.value.toString('utf8'));
                results.push(record);
            }

            if (result.done) {
                await iterator.close();
                break;
            }
        }

        return results;
    }

    _removeSensitiveWalletFields(wallet) {
        const safeWallet = Object.assign({}, wallet);

        delete safeWallet.passwordHash;
        delete safeWallet.nationalIdHash;
        delete safeWallet.mobileHash;
        delete safeWallet.emailHash;

        return safeWallet;
    }

    _successResponse(message, data) {
        return {
            success: true,
            message: message,
            data: data
        };
    }
}

module.exports = KycWalletContract;
