

volumes:
  couchdb0_org1_data:
  couchdb0_org2_data:

networks:
  fabric_test:
    external: true
    name: fabric_test

services:

  couchdb0.org1:
    container_name: couchdb0.org1
    image: couchdb:3.3.3
    restart: unless-stopped
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "5984:5984"
    networks:
      - fabric_test
    volumes:
      - couchdb0_org1_data:/opt/couchdb/data
    healthcheck:
      test: ["CMD", "bash", "-c", "curl -f http://admin:adminpw@localhost:5984/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  couchdb0.org2:
    container_name: couchdb0.org2
    image: couchdb:3.3.3
    restart: unless-stopped
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "7984:5984"
    networks:
      - fabric_test
    volumes:
      - couchdb0_org2_data:/opt/couchdb/data
    healthcheck:
      test: ["CMD", "bash", "-c", "curl -f http://admin:adminpw@localhost:5984/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10