/* ============================================================
   STEP 15 — PostgreSQL Integration Setup
   Project: Blockchain Integration Project
   Database: vfds_dev
   Host: 172.31.13.133
   Port: 5444
   Schema: blockchain
   ============================================================ */

BEGIN;

-- ============================================================
-- 1. Required PostgreSQL Extensions
-- ============================================================

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_proc
        WHERE proname = 'gen_random_uuid'
    ) THEN
        RAISE NOTICE 'gen_random_uuid() does not exist. Please install pgcrypto manually if needed.';
    ELSE
        RAISE NOTICE 'gen_random_uuid() already exists. Skipping pgcrypto creation.';
    END IF;
END
$$;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS citext;

-- ============================================================
-- 2. Create Blockchain Schema
-- ============================================================

CREATE SCHEMA IF NOT EXISTS blockchain;

COMMENT ON SCHEMA blockchain IS
'Dedicated schema for Blockchain Integration Project including wallet, transaction, audit, and mapping data.';

-- ============================================================
-- 3. Create Application Role / User
-- ============================================================

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_roles
        WHERE rolname = 'blockchain_app_user'
    ) THEN
        CREATE ROLE blockchain_app_user
        LOGIN
        PASSWORD 'postgres';
    END IF;
END
$$;

COMMENT ON ROLE blockchain_app_user IS
'Application database user used by Blockchain API / Middleware to access blockchain schema.';

-- ============================================================
-- 4. Grant Database and Schema Permissions
-- ============================================================

GRANT CONNECT ON DATABASE vfds_dev TO blockchain_app_user;

GRANT USAGE ON SCHEMA blockchain TO blockchain_app_user;
GRANT CREATE ON SCHEMA blockchain TO blockchain_app_user;

-- Existing object permissions
GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA blockchain
TO blockchain_app_user;

GRANT USAGE, SELECT, UPDATE
ON ALL SEQUENCES IN SCHEMA blockchain
TO blockchain_app_user;

GRANT EXECUTE
ON ALL FUNCTIONS IN SCHEMA blockchain
TO blockchain_app_user;

-- Future object permissions
ALTER DEFAULT PRIVILEGES IN SCHEMA blockchain
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLES TO blockchain_app_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA blockchain
GRANT USAGE, SELECT, UPDATE
ON SEQUENCES TO blockchain_app_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA blockchain
GRANT EXECUTE
ON FUNCTIONS TO blockchain_app_user;

-- ============================================================
-- 5. Customer Mapping Table
-- ============================================================

CREATE TABLE IF NOT EXISTS blockchain.blockchain_customer_mapping (
    mapping_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    blockchain_customer_id VARCHAR(100) NOT NULL,
    source_customer_id VARCHAR(100) NOT NULL,

    customer_reference_type VARCHAR(50) DEFAULT 'KYC_CUSTOMER_ID',

    wallet_address VARCHAR(150),

    customer_hash VARCHAR(255),
    national_id_hash VARCHAR(255),
    mobile_hash VARCHAR(255),
    email_hash VARCHAR(255),

    mapping_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    created_by VARCHAR(100) DEFAULT current_user,
    updated_by VARCHAR(100),

    CONSTRAINT uq_blockchain_customer_mapping_customer
        UNIQUE (blockchain_customer_id),

    CONSTRAINT uq_blockchain_customer_mapping_source_customer
        UNIQUE (source_customer_id),

    CONSTRAINT chk_customer_mapping_status
        CHECK (mapping_status IN ('ACTIVE', 'INACTIVE', 'BLOCKED', 'DELETED'))
);

COMMENT ON TABLE blockchain.blockchain_customer_mapping IS
'Maps blockchain customer IDs and wallet addresses to existing customer/KYC IDs.';

COMMENT ON COLUMN blockchain.blockchain_customer_mapping.blockchain_customer_id IS
'Customer identifier used by blockchain chaincode and Blockchain API.';

COMMENT ON COLUMN blockchain.blockchain_customer_mapping.source_customer_id IS
'Customer identifier from existing core/KYC/customer system.';

COMMENT ON COLUMN blockchain.blockchain_customer_mapping.wallet_address IS
'Wallet address generated by blockchain chaincode.';

-- ============================================================
-- 6. Organization Mapping Table
-- ============================================================

CREATE TABLE IF NOT EXISTS blockchain.blockchain_organization_mapping (
    mapping_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    blockchain_organization_id VARCHAR(100) NOT NULL,
    source_organization_id VARCHAR(100) NOT NULL,

    organization_code VARCHAR(100),
    organization_name VARCHAR(255),

    organization_type VARCHAR(50) DEFAULT 'BANK',

    mapping_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    created_by VARCHAR(100) DEFAULT current_user,
    updated_by VARCHAR(100),

    CONSTRAINT uq_blockchain_org_mapping_blockchain_org
        UNIQUE (blockchain_organization_id),

    CONSTRAINT uq_blockchain_org_mapping_source_org
        UNIQUE (source_organization_id),

    CONSTRAINT chk_org_mapping_status
        CHECK (mapping_status IN ('ACTIVE', 'INACTIVE', 'BLOCKED', 'DELETED')),

    CONSTRAINT chk_org_type
        CHECK (organization_type IN ('BANK', 'MERCHANT', 'GOVERNMENT', 'PARTNER', 'OTHER'))
);

COMMENT ON TABLE blockchain.blockchain_organization_mapping IS
'Maps blockchain organization IDs to existing bank, merchant, government, or partner organization IDs.';

-- ============================================================
-- 7. Blockchain Wallet Integration Table
-- ============================================================

CREATE TABLE IF NOT EXISTS blockchain.blockchain_wallet_integration (
    wallet_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    wallet_address VARCHAR(150) NOT NULL,
    blockchain_customer_id VARCHAR(100) NOT NULL,
    blockchain_organization_id VARCHAR(100),

    customer_name VARCHAR(255),

    wallet_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',

    current_balance NUMERIC(20, 6) NOT NULL DEFAULT 0,
    currency_code VARCHAR(10) NOT NULL DEFAULT 'TOKEN',

    fabric_channel_name VARCHAR(100),
    chaincode_name VARCHAR(100),
    fabric_tx_id VARCHAR(150),

    created_on_blockchain_at TIMESTAMP,
    synced_to_postgres_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_blockchain_wallet_address
        UNIQUE (wallet_address),

    CONSTRAINT chk_wallet_status
        CHECK (wallet_status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'CLOSED', 'BLOCKED'))
);

COMMENT ON TABLE blockchain.blockchain_wallet_integration IS
'PostgreSQL integration copy of blockchain wallet data for API, reporting, and analytics.';

-- ============================================================
-- 8. Blockchain Transaction Integration Table
-- ============================================================

CREATE TABLE IF NOT EXISTS blockchain.blockchain_transaction_integration (
    transaction_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    blockchain_transaction_id VARCHAR(150) NOT NULL,
    fabric_tx_id VARCHAR(150),

    transaction_type VARCHAR(50) NOT NULL,

    from_wallet_address VARCHAR(150),
    to_wallet_address VARCHAR(150),

    from_organization_id VARCHAR(100),
    to_organization_id VARCHAR(100),

    amount NUMERIC(20, 6) NOT NULL,
    currency_code VARCHAR(10) NOT NULL DEFAULT 'TOKEN',

    transaction_status VARCHAR(30) NOT NULL DEFAULT 'SUCCESS',

    risk_level VARCHAR(30) DEFAULT 'LOW',
    risk_score NUMERIC(10, 4),

    transaction_description TEXT,

    fabric_channel_name VARCHAR(100),
    chaincode_name VARCHAR(100),

    blockchain_created_at TIMESTAMP,
    synced_to_postgres_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_blockchain_transaction_id
        UNIQUE (blockchain_transaction_id),

    CONSTRAINT chk_transaction_type
        CHECK (
            transaction_type IN (
                'WALLET_TO_WALLET',
                'WALLET_TO_ORGANIZATION',
                'ORGANIZATION_TO_WALLET',
                'ORGANIZATION_TO_ORGANIZATION',
                'INITIAL_BALANCE',
                'ADJUSTMENT'
            )
        ),

    CONSTRAINT chk_transaction_status
        CHECK (
            transaction_status IN (
                'PENDING',
                'SUCCESS',
                'FAILED',
                'REJECTED',
                'REVERSED'
            )
        ),

    CONSTRAINT chk_risk_level
        CHECK (
            risk_level IN (
                'LOW',
                'MEDIUM',
                'HIGH',
                'CRITICAL'
            )
        )
);

COMMENT ON TABLE blockchain.blockchain_transaction_integration IS
'PostgreSQL integration copy of blockchain transaction data for reporting, analytics, dashboard, and reconciliation.';

-- ============================================================
-- 9. Blockchain Audit Log Table
-- ============================================================

CREATE TABLE IF NOT EXISTS blockchain.blockchain_postgres_audit_log (
    audit_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    event_type VARCHAR(100) NOT NULL,
    event_source VARCHAR(100) NOT NULL DEFAULT 'POSTGRESQL',

    entity_type VARCHAR(100),
    entity_id VARCHAR(150),

    action_name VARCHAR(100),
    action_status VARCHAR(30) NOT NULL DEFAULT 'SUCCESS',

    request_payload JSONB,
    response_payload JSONB,
    error_message TEXT,

    performed_by VARCHAR(100) DEFAULT current_user,
    performed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    client_ip VARCHAR(100),
    api_endpoint VARCHAR(255),

    fabric_tx_id VARCHAR(150),
    wallet_address VARCHAR(150),
    blockchain_customer_id VARCHAR(100)
);

COMMENT ON TABLE blockchain.blockchain_postgres_audit_log IS
'Audit table for PostgreSQL-side blockchain integration events, API calls, sync operations, and errors.';

-- ============================================================
-- 10. Event Sync Status Table
-- ============================================================

CREATE TABLE IF NOT EXISTS blockchain.blockchain_event_sync_status (
    sync_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    fabric_tx_id VARCHAR(150) NOT NULL,
    event_name VARCHAR(100) NOT NULL,

    event_payload JSONB,

    sync_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',

    retry_count INTEGER NOT NULL DEFAULT 0,
    max_retry_count INTEGER NOT NULL DEFAULT 3,

    error_message TEXT,

    received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP,

    CONSTRAINT uq_blockchain_event_sync_fabric_tx
        UNIQUE (fabric_tx_id, event_name),

    CONSTRAINT chk_event_sync_status
        CHECK (
            sync_status IN (
                'PENDING',
                'PROCESSING',
                'SUCCESS',
                'FAILED',
                'RETRY'
            )
        )
);

COMMENT ON TABLE blockchain.blockchain_event_sync_status IS
'Tracks synchronization status of Hyperledger Fabric events into PostgreSQL.';

-- ============================================================
-- 11. Indexes
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_customer_mapping_blockchain_customer_id
ON blockchain.blockchain_customer_mapping (blockchain_customer_id);

CREATE INDEX IF NOT EXISTS idx_customer_mapping_source_customer_id
ON blockchain.blockchain_customer_mapping (source_customer_id);

CREATE INDEX IF NOT EXISTS idx_customer_mapping_wallet_address
ON blockchain.blockchain_customer_mapping (wallet_address);

CREATE INDEX IF NOT EXISTS idx_org_mapping_blockchain_org_id
ON blockchain.blockchain_organization_mapping (blockchain_organization_id);

CREATE INDEX IF NOT EXISTS idx_org_mapping_source_org_id
ON blockchain.blockchain_organization_mapping (source_organization_id);

CREATE INDEX IF NOT EXISTS idx_wallet_integration_wallet_address
ON blockchain.blockchain_wallet_integration (wallet_address);

CREATE INDEX IF NOT EXISTS idx_wallet_integration_customer_id
ON blockchain.blockchain_wallet_integration (blockchain_customer_id);

CREATE INDEX IF NOT EXISTS idx_wallet_integration_org_id
ON blockchain.blockchain_wallet_integration (blockchain_organization_id);

CREATE INDEX IF NOT EXISTS idx_transaction_blockchain_tx_id
ON blockchain.blockchain_transaction_integration (blockchain_transaction_id);

CREATE INDEX IF NOT EXISTS idx_transaction_fabric_tx_id
ON blockchain.blockchain_transaction_integration (fabric_tx_id);

CREATE INDEX IF NOT EXISTS idx_transaction_from_wallet
ON blockchain.blockchain_transaction_integration (from_wallet_address);

CREATE INDEX IF NOT EXISTS idx_transaction_to_wallet
ON blockchain.blockchain_transaction_integration (to_wallet_address);

CREATE INDEX IF NOT EXISTS idx_transaction_status
ON blockchain.blockchain_transaction_integration (transaction_status);

CREATE INDEX IF NOT EXISTS idx_transaction_risk_level
ON blockchain.blockchain_transaction_integration (risk_level);

CREATE INDEX IF NOT EXISTS idx_transaction_created_at
ON blockchain.blockchain_transaction_integration (created_at);

CREATE INDEX IF NOT EXISTS idx_audit_event_type
ON blockchain.blockchain_postgres_audit_log (event_type);

CREATE INDEX IF NOT EXISTS idx_audit_entity
ON blockchain.blockchain_postgres_audit_log (entity_type, entity_id);

CREATE INDEX IF NOT EXISTS idx_audit_performed_at
ON blockchain.blockchain_postgres_audit_log (performed_at);

CREATE INDEX IF NOT EXISTS idx_event_sync_status
ON blockchain.blockchain_event_sync_status (sync_status);

CREATE INDEX IF NOT EXISTS idx_event_sync_fabric_tx_id
ON blockchain.blockchain_event_sync_status (fabric_tx_id);

-- JSONB indexes
CREATE INDEX IF NOT EXISTS idx_audit_request_payload_gin
ON blockchain.blockchain_postgres_audit_log
USING GIN (request_payload);

CREATE INDEX IF NOT EXISTS idx_audit_response_payload_gin
ON blockchain.blockchain_postgres_audit_log
USING GIN (response_payload);

CREATE INDEX IF NOT EXISTS idx_event_payload_gin
ON blockchain.blockchain_event_sync_status
USING GIN (event_payload);

-- ============================================================
-- 12. Trigger Function for updated_at
-- ============================================================

CREATE OR REPLACE FUNCTION blockchain.fn_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

-- ============================================================
-- 13. Triggers
-- ============================================================

DROP TRIGGER IF EXISTS trg_customer_mapping_updated_at
ON blockchain.blockchain_customer_mapping;

CREATE TRIGGER trg_customer_mapping_updated_at
BEFORE UPDATE ON blockchain.blockchain_customer_mapping
FOR EACH ROW
EXECUTE FUNCTION blockchain.fn_set_updated_at();

DROP TRIGGER IF EXISTS trg_org_mapping_updated_at
ON blockchain.blockchain_organization_mapping;

CREATE TRIGGER trg_org_mapping_updated_at
BEFORE UPDATE ON blockchain.blockchain_organization_mapping
FOR EACH ROW
EXECUTE FUNCTION blockchain.fn_set_updated_at();

DROP TRIGGER IF EXISTS trg_wallet_integration_updated_at
ON blockchain.blockchain_wallet_integration;

CREATE TRIGGER trg_wallet_integration_updated_at
BEFORE UPDATE ON blockchain.blockchain_wallet_integration
FOR EACH ROW
EXECUTE FUNCTION blockchain.fn_set_updated_at();

-- ============================================================
-- 14. Useful Integration View
-- ============================================================

CREATE OR REPLACE VIEW blockchain.vw_blockchain_customer_wallet AS
SELECT
    cm.mapping_id,
    cm.blockchain_customer_id,
    cm.source_customer_id,
    cm.wallet_address,
    cm.mapping_status,
    wi.customer_name,
    wi.blockchain_organization_id,
    wi.wallet_status,
    wi.current_balance,
    wi.currency_code,
    wi.fabric_channel_name,
    wi.chaincode_name,
    wi.fabric_tx_id,
    wi.created_on_blockchain_at,
    wi.synced_to_postgres_at
FROM blockchain.blockchain_customer_mapping cm
LEFT JOIN blockchain.blockchain_wallet_integration wi
    ON wi.wallet_address = cm.wallet_address;

COMMENT ON VIEW blockchain.vw_blockchain_customer_wallet IS
'Unified customer-wallet integration view for Blockchain API and reporting.';

GRANT SELECT ON blockchain.vw_blockchain_customer_wallet TO blockchain_app_user;

-- ============================================================
-- 15. Sample Seed Data for Testing
-- ============================================================

INSERT INTO blockchain.blockchain_organization_mapping (
    blockchain_organization_id,
    source_organization_id,
    organization_code,
    organization_name,
    organization_type
)
VALUES
(
    'BANK001',
    'BANK001',
    'BANK001',
    'Default Test Bank',
    'BANK'
)
ON CONFLICT (blockchain_organization_id)
DO NOTHING;

INSERT INTO blockchain.blockchain_customer_mapping (
    blockchain_customer_id,
    source_customer_id,
    wallet_address,
    customer_hash,
    mapping_status
)
VALUES
(
    'CUST1002',
    'CUST1002',
    'WALLET_77AE48A0CA2BD9C5BE97EB0AECF_TEST',
    'NID_HASH_1002',
    'ACTIVE'
)
ON CONFLICT (blockchain_customer_id)
DO NOTHING;

INSERT INTO blockchain.blockchain_wallet_integration (
    wallet_address,
    blockchain_customer_id,
    blockchain_organization_id,
    customer_name,
    wallet_status,
    current_balance,
    currency_code,
    fabric_channel_name,
    chaincode_name,
    fabric_tx_id,
    created_on_blockchain_at
)
VALUES
(
    'WALLET_77AE48A0CA2BD9C5BE97EB0AECF_TEST',
    'CUST1002',
    'BANK001',
    'Nicolas Salloum',
    'ACTIVE',
    1000,
    'TOKEN',
    'kycchannelnix1',
    'kyc-wallet-chaincode-js',
    'TEST_FABRIC_TX_1002',
    CURRENT_TIMESTAMP
)
ON CONFLICT (wallet_address)
DO NOTHING;

COMMIT;
