#!/bin/bash

# ==========================================================
# PostgreSQL Safe Delete Script
# Delete table by table
# Commit after each successful table
# Skip table if error happens
# ==========================================================

DB_HOST="172.31.13.133"
DB_PORT="5444"
DB_NAME="icm_dev"
DB_USER="postrges"

# Optional:
export PGPASSWORD="postgres"

TABLES=(
"FINDBA.FIN_TRANSACTION"
"SDEDBA.REF_CUSTOMER"
"FINDBA.FIN_ACCOUNT_INFO"
"SDEDBA.REF_CUSTOMER_MISC_INFO"
"SDEDBA.CFG_CUSTOMER_DEF"
"SUITEDBA.CFG_OBJECT_API_DEF"

"FINDBA.FIN_TRANSACTION_BACKUP"
"FINDBA.TRANSACTIONS"
"FINDBA.ACCOUNT"
"FINDBA.FIN_ACCOUNT_INFO_TEST"
"FINDBA.FIN_TRANSACTION_TEST"
"FINDBA.TMP_ACCT_REJ_RULE1_DUPLICATES"
"FINDBA.TMP_ACCT_REJ_RULE2_MANDATORY"
"FINDBA.TMP_ACCT_REJ_RULE4_OLD_DATES"
"FINDBA.TMP_VALID_ACCOUNTS"
"FINDBA.TMP_TXN_REJ_RULE1_DUPLICATES"
"FINDBA.TMP_TXN_REJ_RULE2_MANDATORY"
"FINDBA.TMP_TXN_REJ_RULE4_OLD_DATES"
"FINDBA.TMP_VALID_TRANSACTIONS"
"FINDBA.BLOCKCHAIN_TRANSFERS"
"FINDBA.CDS_MAPPING_REPORT_MENU"
"FINDBA.FIN_ACCOUNT_BALANCE"
"FINDBA.FIN_ACCOUNT_ITEM"
"FINDBA.FIN_BUDGET_DEFINITION"
"FINDBA.FIN_CHEQUE_INFO"
"FINDBA.FIN_EXPENSE"
"FINDBA.FIN_LGCY_ACCOUNT_INFO"
"FINDBA.FIN_LGCY_TRX_CHARGE_INFO"
"FINDBA.FIN_OPERATION_TYPE"
"FINDBA.FIN_PAR_ACCOUNT_GROUP_TYPE"
"FINDBA.FIN_PAR_ACT_TYPE_GROUP_LINK"
"FINDBA.FIN_PAR_BUDGET_TYPE"
"FINDBA.FIN_PAR_EXPENSE_TYPE"
"FINDBA.FIN_PAR_SWIFT_FREETEXT_MAP"
"FINDBA.FIN_PAR_SWIFT_MSG_FIELD_MAP"
"FINDBA.FIN_PAYMENT"
"FINDBA.FIN_RISK_MATRIX_ATTR_D_EXP"
"FINDBA.FIN_RISK_MATRIX_ATTR_GRP_EXP"
"FINDBA.FIN_RISK_MATRIX_ATTRIBUTE_D"
"FINDBA.FIN_RISK_MATRIX_ATTRIBUTE_GRP"
"FINDBA.FIN_RISK_MATRIX_ATTRIBUTE_M"
"FINDBA.FIN_RSK_MTRX_ATR_GRP_PRTY_TYP"
"FINDBA.FIN_RSK_MTRX_ATR_PRTY_TYP_DTL"
"FINDBA.FIN_RSK_MTRX_ATR_PRTY_TYP_EXP"
"FINDBA.FIN_CONTRACT"
"FINDBA.FIN_RSK_MTRX_ATR_PRTY_TYP_HIS"
"FINDBA.FIN_RSK_MTRX_ATR_PRTY_TYP_MSTR"
"FINDBA.FIN_SWIFT_FIELD_PRTY_TYP_EXCP"
"FINDBA.FIN_SWIFT_FILE_ERROR"
"FINDBA.FIN_SWIFT_INFO"
"FINDBA.FIN_SWIFT_MAP_FIELD_SANCTN_SRC"
"FINDBA.FIN_SWIFT_MAPPING"
"FINDBA.FIN_SWIFT_MAPPING_FIELD_EXCP"
"FINDBA.FIN_SWIFT_MAPPING_PEP"
"FINDBA.FIN_SWIFT_MESSAGE_TYPE"
"FINDBA.FIN_SWIFT_SANCTION_MATCH_HIS"
"FINDBA.FIN_TRANS_TYPE_CAT1"
"FINDBA.FIN_TRANS_TYPE_CAT2"
"FINDBA.FIN_TRANS_TYPE_CAT3"
"FINDBA.FIN_TRANS_TYPE_CAT4"
"FINDBA.FIN_TRANSACTION_100"
"FINDBA.FIN_TRANSACTION_BUSINESS_RULE"
"FINDBA.FIN_TRANSACTION_CHARGE_INFO"
"FINDBA.FIN_TRANSACTION_COMU_CHANNEL"
"FINDBA.FIN_TRANSACTION_DSTAT"
"FINDBA.FIN_TRANSACTION_EDUCATION_INFO"
"FINDBA.FIN_TRANSACTION_GLOBAL_INFO"
"FINDBA.FIN_TRANSACTION_GLOBAL_INFO_TEST"
"FINDBA.FIN_TRANSACTION_HIS"
"FINDBA.FIN_TRANSACTION_MULTIMEDIA"
"FINDBA.FIN_TRANSACTION_PAYMENT"
"FINDBA.FIN_TRANSACTION_TRACKING"
"FINDBA.FIN_TRANSACTION_VIEW"
"FINDBA.FIN_TRANSCTION_CATEGORY"
"FINDBA.FIN_TRANSCTION_GROUPING"
"FINDBA.FIN_TRANSCTION_TYPE"
"FINDBA.FIN_TRANSCTION_TYPE_GROUPING"
"FINDBA.FIN_TRX_ITEM_VEN_COU_FIELD"
"FINDBA.REF_ITEM"
"FINDBA.V_ARABIC_ALPHABET"
"FINDBA.V_GET_WEEK_MONTH"
"FINDBA.V_MECHANIC_WS_ATTRIBUTES"
"FINDBA.FIN_PAR_ACCOUNT_TYPE"

"ANLDBA.CHECK_AML_DATA"
"ANLDBA.VCHAT_NOTES"
"ANLDBA.REG_DESCRIPTION"
"ANLDBA.REPORT_ELEMENTS"
"ANLDBA.REPORT_DETAILS"
"ANLDBA.SSDX_RPT_BDLREP_INDATA20250331"
"ANLDBA.REPORTS"
"ANLDBA.V_CHAT_MEMORY"
"ANLDBA.VFDS_GEO_REPORT"
"ANLDBA.MESSAGES"
"ANLDBA.KG_DATA"
"ANLDBA.REPORT_EXCEL_DATA"
"ANLDBA.BBSC_BCC_FAC_TYPES"
"ANLDBA.BBSC_BCC_RETAILS_TYPE"
"ANLDBA.BBSC_BCC_ECO_SECTORS"
"ANLDBA.BBSC_BCC_SUBECO_SECTORS"
"ANLDBA.BBSC_BCC_IFRS9_LRATING"
"ANLDBA.BBSC_BCC_COLL_TYPES"
"ANLDBA.SSDX_FRB_AUTHORIZATION20251231"
"ANLDBA.SSDX_FRB_ACC_GUARANTEE20251231"
"ANLDBA.SSDX_RPT_BDLREP_INDATA20251231"
"ANLDBA.CONFIGURATION_REGAI_V2_TEMP_2"
"ANLDBA.BBSC_BCC_FACILITY_PURPOSE_LIST"
"ANLDBA.LPD_CLIENT"
"ANLDBA.LPD_NEW_MAPPING_COCB"
"ANLDBA.LPD_NEW_MAPPING_CORT"
"ANLDBA.LPD_NEW_MAPPING_LNCB"
"ANLDBA.LPD_NEW_MAPPING_LNCF"
"ANLDBA.LPD_NEW_MAPPING_LNRT"
"ANLDBA.REG_REPORT_SCOPE"
"ANLDBA.REG_REPORT_STATUS"
"ANLDBA.REG_REPORT_AFFECTED_INSTITUTIONS"
"ANLDBA.REPORT_SHEETS"
"ANLDBA.REF_COM_LEDGER_DEF"
"ANLDBA.BBSC_CURRENCIES"
"ANLDBA.BBSC_BCC_LOAN_RISK_PERC"
"ANLDBA.BBSC_BCC_RESIDENTS"
"ANLDBA.BBSC_BCC_BRANCH_COUNTRIES"
"ANLDBA.BBSC_BCC_CLIENT_TYPE"
"ANLDBA.BBSC_BCC_LOAN_RISK_TYPES"
"ANLDBA.S_LPF_CORT"
"ANLDBA.REPORT_DIFF_HTML"
"ANLDBA.REG_REPORT_REGULATION_TYPE"
"ANLDBA.REG_REPORT_ARTICLE_TYPE"
"ANLDBA.REPORT_TEXT_EXTRACTION"
"ANLDBA.SSDX_FRB_ACC_GUARANTEE20250228"
"ANLDBA.SSDX_FRB_SCHEDULE_LOAN20250228"
"ANLDBA.CONFIGURATION_REGAI_V2"
"ANLDBA.REG_REPORT_URLS"
"ANLDBA.REG_REPORT_PDFS"
"ANLDBA.CHECKPOINT_MIGRATIONS"
"ANLDBA.CHECKPOINTS"
"ANLDBA.CHECKPOINT_BLOBS"
"ANLDBA.CHECKPOINT_WRITES"
"ANLDBA.CONFIGURATION_REGAI_V2_TEMP"
"ANLDBA.CONFIGURATION_REGAI"
"ANLDBA.REPORT_DETAILS_HTML"
"ANLDBA.CONFIGURATION_REGAI_V2_TEMP_3"
"ANLDBA.REPORT_KEYWORDS"
"ANLDBA.REPORT_CLAUSE"
"ANLDBA.REF_COM_LEDGER_DEF2"
"ANLDBA.REG_LAWS_CONFIG"
"ANLDBA.REF_MSE_BSN_SUB_MSE"
"ANLDBA.CFG_FILE_MAPPING_SRC_PARAM"
"ANLDBA.REF_MSE_STRU_ELEM"
"ANLDBA.REG_LAWS_CONFIG_2"
"ANLDBA.CFG_FILE_MAPPING_DEF"
"ANLDBA.CFG_FILE_MAPPING_FILTER"
"ANLDBA.VCIS_DOCUMENT_CHUNKS"
"ANLDBA.CFG_FILE_MAPPING_DST_PARAM"
"ANLDBA.CFG_FILE_MAPPING_FILTER_GROUP"
"ANLDBA.META_INT_COLUMN"
"ANLDBA.ACTION_DETAILS"
"ANLDBA.S_LPF_LNRT"
"ANLDBA.SSDX_RPT_BDLREP_INDATA20251231_TESTING_2"
"ANLDBA.SSDX_FRB_ACCOUNTS_MOUVEMENT"
"ANLDBA.SSDX_FRB_ACCOUNTS_EXCLUS"
"ANLDBA.SSDX_FRB_LC_UTILIZATION"
"ANLDBA.SSDX_FRB_SCHEDULE_LOAN20251231"
"ANLDBA.SSDX_FRB_LC_ACCEPTANCE"
"ANLDBA.SSDX_FRB_ACCOUNT_DAILLY"
"ANLDBA.SSDX_FRB_BANK_OPE"
"ANLDBA.SSDX_FRB_BDL_REFERENCE"
"ANLDBA.SSDX_FRB_ACCOUNTS_TB"
"ANLDBA.SSDX_FRB_CORRESPONDANT_BANKS"
"ANLDBA.SSDX_RPT_BDLREP_INDATA20251231_TESTING"
"ANLDBA.S_LPF_COCB"
"ANLDBA.S_LPF_LNCB"
"ANLDBA.S_LPF_LNCF"
"ANLDBA.SUSPECT_EMBEDDINGS"
)

TOTAL=${#TABLES[@]}
SUCCESS_COUNT=0
SKIP_COUNT=0
CURRENT=0

echo "===================================================="
echo " PostgreSQL Delete Engine Started"
echo " Database : $DB_NAME"
echo " Host     : $DB_HOST"
echo " Port     : $DB_PORT"
echo " User     : $DB_USER"
echo " Tables   : $TOTAL"
echo "===================================================="
echo ""

for TABLE in "${TABLES[@]}"; do
    CURRENT=$((CURRENT + 1))

    SCHEMA_NAME="${TABLE%%.*}"
    TABLE_NAME="${TABLE#*.}"

    echo "----------------------------------------------------"
    echo "[$CURRENT/$TOTAL] START DELETE: $TABLE"
    echo "----------------------------------------------------"

    psql \
      -h "$DB_HOST" \
      -p "$DB_PORT" \
      -U "$DB_USER" \
      -d "$DB_NAME" \
      -v ON_ERROR_STOP=1 \
      -v schema_name="$SCHEMA_NAME" \
      -v table_name="$TABLE_NAME" <<'SQL'

SET session_replication_role = replica;

DO $$
DECLARE
    v_schema text := :'schema_name';
    v_table  text := :'table_name';
    v_regclass regclass;
    v_before bigint := 0;
BEGIN
    -- Try uppercase / original name
    v_regclass := to_regclass(format('%I.%I', v_schema, v_table));

    -- Try lowercase name
    IF v_regclass IS NULL THEN
        v_regclass := to_regclass(format('%I.%I', lower(v_schema), lower(v_table)));
    END IF;

    IF v_regclass IS NULL THEN
        RAISE EXCEPTION 'Table not found: %.%', v_schema, v_table;
    END IF;

    EXECUTE format('SELECT COUNT(*) FROM %s', v_regclass)
    INTO v_before;

    EXECUTE format('DELETE FROM %s', v_regclass);

    RAISE NOTICE 'Deleted % rows from %', v_before, v_regclass;
END $$;

SET session_replication_role = DEFAULT;

SQL

    STATUS=$?

    if [ $STATUS -eq 0 ]; then
        SUCCESS_COUNT=$((SUCCESS_COUNT + 1))
        echo "FINISHED + COMMITTED: $TABLE"
    else
        SKIP_COUNT=$((SKIP_COUNT + 1))
        echo "SKIPPED DUE TO ERROR: $TABLE"
    fi

    echo ""
done

echo "===================================================="
echo " PostgreSQL Delete Engine Finished"
echo "===================================================="
echo "Total Tables      : $TOTAL"
echo "Finished/Committed: $SUCCESS_COUNT"
echo "Skipped/Error     : $SKIP_COUNT"
echo "===================================================="