--Query 1 -- Dashboard -- Total Wallets
SELECT COUNT(*)
FROM BLOCKCHAIN.WALLETS 

--Query 2 -- Dashboard -- Active Wallets
SELECT COUNT(*)
FROM BLOCKCHAIN.WALLETS
WHERE STATUS = 'ACTIVE' 

--Query 3 -- Dashboard -- Wallet Records
SELECT CUSTOMER_ID AS "Customer ID",
	WALLET_ADDRESS AS "Wallet Address",
	FULL_NAME AS "Full Name",
	ORGANIZATION_CODE AS "Organization",
	CURRENT_BALANCE AS "Balance",
	STATUS AS "Status",
	CREATED_AT AS "Created At"
FROM BLOCKCHAIN.WALLETS

--Query 4 -- Wallet Create -- Organization Types
SELECT DISTINCT ORGANIZATION_TYPE_ID AS ID,
	ORGANIZATION_TYPE AS NAME
FROM BLOCKCHAIN.BLOCKCHAIN_ORGANIZATION
ORDER BY ORGANIZATION_TYPE_ID

--Query 5 -- Wallet Create -- Organizations by Type
SELECT ORGANIZATION_CODE AS ID,
	ORGANIZATION_NAME AS NAME
FROM BLOCKCHAIN.BLOCKCHAIN_ORGANIZATION
WHERE ORGANIZATION_TYPE_ID =[PARAMETER]

--Query 6 -- Wallet Create -- Currencies
SELECT CUR_ID AS ID,
	ISO_CUR_CODE AS NAME
FROM SDEDBA.REF_COM_CURRENCY
WHERE ISO_CUR_CODE IN ('USD','LBP','EUR')

--Query 7 -- Wallet Create -- Countries
SELECT COU_ID AS ID,
	COU_NAME AS NAME
FROM SDEDBA.REF_COM_COUNTRY

--Query 8 -- Wallet Create -- Countries_Code
SELECT COU_ID
FROM SDEDBA.REF_COM_COUNTRY
WHERE COU_NAME = [PARAMETER]

--Query 9 -- Wallet Create -- Generate Customer ID
SELECT NEXTVAL('sdedba.s_customer')::numeric AS CUSTOMER_ID	

